language: java
jdk: openjdk8
install: true
script: mvn package
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: releases
    api_key:
      secure: v/BAROf/wzGGctycRfnGCQ3mEuam4O8Wfe7y4CGm9O3+G3HsgpgtjTv0JMWFqMvJ6zoscXVrTIUlwPmtOJ+oJSTclLqPWMrbraYFxlAL6II/vPlg/wIq4vS5ix8wENdZK/T0DSyhjedF9wYmBX9mdkSwQaSrKxIoO95sLUNvR8t57uW6iyHTMqS1EqT81A5WPqAjjgw9GO5VyPTnhlsfIuJE21LST1Ia3H1ZqmSudCY8re0E4qgOHuTcBCAv63alKqbBIRB3KJeXfmDRvpp6yqrwHI6aG4KUUWwhmekUkFXgPvp+jZ5Pm2nMkp9TsCqqIiwVQTBnKTcafFx2Lz99Icv3ALwhQof3/GSKGZI+hT4MSSy95SHW3aIzMqjrjfRaPbYEuYjkAp1Qu+WuJsWZwJC2DU8AzsG2+FCdDGXEY7Zv0VdkpEDbhRHL3PBzbRY5vqTHHvZGgvWykoeob0SEyBnGjNIwhIFBrO67LjRynLyOxc5F4e7kC+EHc5Nn5PDm27F+x+uspGT9WHyFBNKrolHlCah0I6SKAchRA9mA6WGSlirSCnU3uRN1SZKvDYn++foMfRPJIo/mQWoHDSpzP6NeFlBcD15IR7Wq+ZXPdCijYyzVJKy/NCydaLr4mGwxJoRVMvnNmJuvCZaECrIddHTSYP2JLVK0jdzvuJYCPDU=
    file_glob: true
    file: hercules-*/target/hercules-*.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script:
      - make services_images
    on:
      tags: true
notifications:
  slack:
    secure: 6TPq5PaOr2jW2/DUF5AcWmw48s+MVmRfknA1G93VxObGerkXAO4qZjVAFX+1tHJicGNwD0K2ELiwkbDRlBf1HuA2muVR9lWVH08XyssVrLfU5OZMv9v9HCoUW3IqiNwVr2vwNp/yL+3Sa3HgV37npj9njT62R+QLxfat63vndIcbJFxwlFW5ozIjjEOsJn0FwbHAcXm5Kr6BzQ/wJk/wu7oARjuzY1BFfzz3cOLwF1qAte7FG+TErIY1QtYXCLxGgjoXb2ZTtnm4JalR/mxTLL9kdVbo9Iu6zbvaEylIOUv1c4zDUsEYlSegVaoEgZE1iE5rH5HBididq2CKIXO5bcOr7r0/XdicLarcay64FduUVr0Dg7UoliEoGeR03vFentKXuAQBL2MYv9wXrY08ZGWyPsAVHuhZY8hxL4XdWAv2o66C9Mq5DSeSvgeVWOqtzY2cxh1xRCMVdbwjaQB10MTPjN2WRs76AdUj6gVjLhBLxuStoS/ALxWNhgGsOIzbZV6zqCKDpNbmePP+S3Xoo3ctTMV55KzIG0BFibYeAFyd4k5HT76psBI51gVT7vpXdm7xxLi+Ad+snJFzRm0j7/5fb2DGyV9skpTlEIooE0YnPolIEkikDSG2GgetlQRif5TQ3mOm0hVqU3AufTBGQJufFV+VoQqS1uYVQQmLnSU=

